function initialActorPose = helperInitializeVehiclePose(spacing,velocity,tractorTrailerParameters,vehicleDimension)
% Helper function to initialize the pose of the tractor and trailer of
% leader, follower1 and follower2 in the straight road scene.
%
% This is a helper script for example purposes and may be removed or
% modified in the future.
% 
% Copyright 2022 The MathWorks, Inc.


% Distance between trailer CG to tractor CG
trailerCgToTractorCgDist = tractorTrailerParameters.TRA.HitchDistance + tractorTrailerParameters.VEH.HitchDistance;
% Distance between tractor CG to tractor front
tractorCgToFront = tractorTrailerParameters.VEH.FrontAxlePositionfromCG + 1.3; % (CG to front axle + front over hang)
% Distance between trailer end to trailer CG
trailerEndToCg = 11.99-tractorTrailerParameters.TRA.HitchDistance; % (Trailer End To Hitch - Trailer CG To Hitch)

% Default Position of CG of Follower 2 Trailer
defaultPositionFollower2Trailer = [-100 2 0];
% Default Position of CG of Follower 2 Tractor
defaultPositionFollower2Tractor = defaultPositionFollower2Trailer+[trailerCgToTractorCgDist 0 0];

% Position of CG of Follower 1 Trailer
positionFollower1Trailer = defaultPositionFollower2Tractor + [tractorCgToFront+spacing.Follower1ToFollower2+trailerEndToCg 0 0];
% Position of CG of Follower 1 Tractor
positionFollower1Tractor = positionFollower1Trailer + [trailerCgToTractorCgDist 0 0];

% Position of CG of Leader Trailer
positionLeaderTrailer = positionFollower1Tractor + [tractorCgToFront+spacing.LeaderToFollower1+trailerEndToCg 0 0];
% Position of CG of Leader Tractor
positionLeaderTractor = positionLeaderTrailer + [trailerCgToTractorCgDist 0 0];

tractorLength = vehicleDimension.TractorLength;
trailerLength = vehicleDimension.TrailerLength;
width = vehicleDimension.Width;
% Initial Pose of Leader Tractor
initialActorPose(1) = struct('ActorID',1,'ClassID', 2, ...
                             'Position',positionLeaderTractor, ...
                             'Velocity',[velocity.Leader 0 0], ...
                             'Acceleration',zeros(1,3), ...
                             'Roll', 0,'Pitch', 0,'Yaw', 0, ...
                             'AngularVelocity', zeros(1,3), ...
                             'Length',tractorLength, 'Width',width);
% Initial Pose of Leader Trailer
initialActorPose(2) = struct('ActorID',2,'ClassID', 8, ...
                             'Position',positionLeaderTrailer, ...
                             'Velocity',[velocity.Leader 0 0], ...
                             'Acceleration',zeros(1,3), ...
                             'Roll', 0,'Pitch', 0,'Yaw', 0, ...
                             'AngularVelocity', zeros(1,3), ...
                             'Length',trailerLength, 'Width',width);

% Initial Pose of Follower 1 Tractor
initialActorPose(3) = struct('ActorID',3,'ClassID', 2, ...
                             'Position',positionFollower1Tractor, ...
                             'Velocity',[velocity.Follower1 0 0], ...
                             'Acceleration',zeros(1,3), ...
                             'Roll', 0,'Pitch', 0,'Yaw', 0, ...
                             'AngularVelocity', zeros(1,3), ...
                             'Length',tractorLength, 'Width',width);
% Initial Pose of Follower 1 Trailer
initialActorPose(4) = struct('ActorID',4,'ClassID', 8, ...
                             'Position',positionFollower1Trailer, ...
                             'Velocity',[velocity.Follower1 0 0], ...
                             'Acceleration',zeros(1,3), ...
                             'Roll', 0,'Pitch', 0,'Yaw', 0, ...
                             'AngularVelocity', zeros(1,3), ...
                             'Length',trailerLength, 'Width',width);

% Initial Pose of Follower 2 Tractor
initialActorPose(5) = struct('ActorID',5,'ClassID', 2, ...
                             'Position',defaultPositionFollower2Tractor, ...
                             'Velocity',[velocity.Follower2 0 0], ...
                             'Acceleration',zeros(1,3), ...
                             'Roll', 0,'Pitch', 0,'Yaw', 0, ...
                             'AngularVelocity', zeros(1,3), ...
                             'Length',tractorLength, 'Width',width);
% Initial Pose of Follower 2 Trailer
initialActorPose(6) = struct('ActorID',6,'ClassID', 8, ...
                             'Position',defaultPositionFollower2Trailer, ...
                             'Velocity',[velocity.Follower2 0 0], ...
                             'Acceleration',zeros(1,3), ...
                             'Roll', 0,'Pitch', 0,'Yaw', 0, ...
                             'AngularVelocity', zeros(1,3), ...
                             'Length',trailerLength, 'Width',width);
end